spring:
  datasource:
    url: "jdbc:postgresql://localhost:5432/simbir"
    username: "postgres"
    password: "postgres"
  jpa:
    hibernate:
      ddl-auto: validate
springdoc:
  swagger-ui:
    path: "/docs"