GET http://localhost:8080/accounts/me
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcmcuamV1Z2VuZWRldi5zaW1iaXIudXRpbHMiLCJleHAiOjE2OTc0NzE0NTEsImlhdCI6MTY5NzQ3MDU1MSwidXNlcm5hbWUiOiJZQ2I0QWZzbWdxMG8zVXBBZWkzM2VPczZsU3V0Skp3YiIsInBhc3N3b3JkIjoicXRhWmNOQnh1VkdEQkpVdjJhd2JnT09IMDM1dEZJQ1oiLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.rXWSnomWP6IcU95wwPhfVk04fYLZnlB8rrebmP3HaTs

