GET http://localhost:8080/accounts/me
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJvcmcuamV1Z2VuZWRldi5zaW1iaXIudXRpbHMiLCJleHAiOjE2OTcwNTMwMjAsImlhdCI6MTY5NzA1MjEyMCwidXNlcm5hbWUiOiJZQ2I0QWZzbWdxMG8zVXBBZWkzM2VPczZsU3V0Skp3YiIsInBhc3N3b3JkIjoicXRhWmNOQnh1VkdEQkpVdjJhd2JnT09IMDM1dEZJQ1oiLCJyb2xlIjoiUk9MRV9BRE1JTiJ9.3obZHTxxPgq933zMu9RV4iuKdwfwtJFV7ZdT-mdehjE

